"""
==========================================================================
AgriMind

Dynamic Executor

Module 6 + Module 5F + Module 5G

Workflow

Planner
      ↓
Specialist Agents
      ↓
Collaborative Reasoning
      ↓
Executive Decision
      ↓
Recommendation
      ↓
Explainable Recommendation

Author : AgriMind Team
==========================================================================
"""

import os
import time
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict

from app.governance.trustai import trustai
from app.utils.provider_config import get_provider
from app.learning.continuous_learning_engine import continuous_learning_engine

from app.reasoning.collaborative_engine import collaborative_engine

from app.agents.weather_agent import weather_agent
from app.agents.soil_agent import soil_agent
from app.agents.satellite_agent import satellite_agent
from app.agents.market_agent import market_agent
from app.agents.historical_agent import historical_agent

from app.executive.executive_agent import executive_agent

from app.agents.recommendation_agent import recommendation_agent

from app.explainability.explanation_engine import (
    explanation_engine
)

logger = logging.getLogger(__name__)


##########################################################################
# Specialist Concurrency
#
# Specialists have no ordering constraint between them, so they run
# concurrently by default. Set AGRIMIND_PARALLEL_SPECIALISTS=0 to force
# the original sequential path -- useful when debugging a single agent,
# or when reproducing a run whose per-agent latencies were measured
# without contention.
##########################################################################

PARALLEL_SPECIALISTS = os.getenv(
    "AGRIMIND_PARALLEL_SPECIALISTS",
    "1"
).strip().lower() not in ("0", "false", "no")

MAX_SPECIALIST_WORKERS = int(
    os.getenv(
        "AGRIMIND_MAX_SPECIALIST_WORKERS",
        "5"
    )
)


class DynamicExecutor:

    """
    Executes the execution plan generated by the planner.

    Responsibilities

    1. Execute specialist agents

    2. Run collaborative reasoning

    3. Generate executive decision

    4. Generate recommendation

    5. Generate explainability report

    6. Return complete execution result
    """

    ####################################################################
    # Agent Registry
    ####################################################################

    def __init__(self):

        self.agent_registry = {

            "WeatherAgent":

                weather_agent,

            "SoilAgent":

                soil_agent,

            "SatelliteAgent":

                satellite_agent,

            "MarketAgent":

                market_agent,

            "HistoricalAgent":

                historical_agent

        }

    ####################################################################
    # Execute Specialist Agents
    ####################################################################

    def execute_specialists(

        self,

        execution_plan,

        context

    ):

        ############################################################
        # Specialists are mutually independent -- each one reads the
        # shared context and produces its own SpecialistOutput, and
        # none of them consumes another's result (fusion happens
        # later, in collaborative reasoning). Running them
        # sequentially therefore paid the sum of five LLM round-trips
        # for work that has no ordering constraint; the measured
        # per-agent latencies (Weather 162s, Soil 258s, Satellite 32s,
        # Market 62s) added up to most of the end-to-end pipeline
        # time.
        #
        # Thread-safety of the shared state they DO touch:
        #   - TrustStateStore guards its mutations with its own
        #     threading.Lock, and each specialist only ever updates
        #     its own agent key, so there is no cross-agent contention.
        #   - TokenRateLimiter is likewise lock-guarded, so Groq
        #     pacing still holds across concurrent callers.
        #
        # Output order is rebuilt from execution_plan afterwards, so
        # results stay deterministic regardless of completion order.
        ############################################################

        planned = []

        for step in execution_plan:

            agent_name = step["agent"]

            ########################################################
            # Skip later-stage agents
            ########################################################

            if agent_name in (

                "ExecutiveAgent",

                "RecommendationAgent"

            ):

                continue

            ########################################################

            if agent_name not in self.agent_registry:

                logger.warning(

                    f"Unknown agent '{agent_name}'."

                )

                continue

            planned.append(
                agent_name
            )

        ############################################################

        if not planned:

            return {}

        ############################################################

        if not PARALLEL_SPECIALISTS or len(planned) == 1:

            results = {
                name: self.run_one_specialist(name, context)
                for name in planned
            }

        else:

            results = {}

            with ThreadPoolExecutor(
                max_workers=min(
                    len(planned),
                    MAX_SPECIALIST_WORKERS
                ),
                thread_name_prefix="specialist"
            ) as pool:

                futures = {
                    pool.submit(
                        self.run_one_specialist,
                        name,
                        context
                    ): name
                    for name in planned
                }

                for future in as_completed(
                    futures
                ):

                    name = futures[future]

                    results[name] = future.result()

        ############################################################
        # Rebuild in plan order so downstream stages and the
        # evaluation harness see a stable ordering.
        ############################################################

        return {
            name: results[name]
            for name in planned
            if name in results
        }

    ####################################################################
    # Execute One Specialist
    ####################################################################

    def run_one_specialist(

        self,

        agent_name,

        context

    ):

        logger.info(

            f"Running {agent_name}"

        )

        agent = self.agent_registry[agent_name]

        start = time.time()

        ########################################################
        # TRUSTAI Pre-Execution Review
        #
        # A "reject" decision skips the call outright instead of
        # letting a governance-distrusted agent run -- the only
        # branch here that actually intercepts, as opposed to
        # just annotating the outcome afterward.
        ########################################################

        precheck = trustai.review(agent_name)

        if precheck.decision.action == "reject":

            logger.warning(

                f"TRUSTAI rejected {agent_name}: "
                f"{precheck.decision.rationale}"

            )

            result = {

                "agent":

                    agent_name,

                "status":

                    "rejected",

                "confidence":

                    0,

                "error":

                    "Rejected by TRUSTAI governance: "
                    + precheck.decision.rationale,

                "execution_time":

                    round(
                        time.time() - start,
                        3
                    ),

                "governance":

                    asdict(precheck)

            }

            return result

        ########################################################


        try:

            result = agent.execute(

                context

            )

            result["agent"] = agent_name

            ####################################################
            # Preserve a status the agent set for itself.
            #
            # "unavailable" means the agent ran correctly but its
            # data source produced nothing to analyze. That is a
            # different runtime fact from "completed", and both
            # governance and the limitation generator depend on
            # the distinction.
            ####################################################

            if not str(
                result.get(
                    "status",
                    ""
                )
            ).strip():

                result["status"] = "completed"

            result["execution_time"] = round(

                time.time() - start,

                3

            )

            ########################################################

        except Exception as e:

            logger.exception(e)

            result = {

                "agent":

                    agent_name,

                "status":

                    "failed",

                "confidence":

                    0,

                "error":

                    str(e),

                "execution_time":

                    round(

                        time.time() - start,

                        3

                    )

            }

        ########################################################
        # TRUSTAI Post-Execution Evidence + Posterior Update
        ########################################################

        governance_record = trustai.record_outcome(
            agent_name,
            result
        )

        result["governance"] = asdict(governance_record)

        ########################################################

        return result

    ####################################################################
    # Execute Pipeline
    ####################################################################

    def execute(

        self,

        plan,

        context

    ):
                ############################################################
        # Execute Specialist Agents
        ############################################################

        specialist_outputs = self.execute_specialists(

            plan["execution_plan"],

            context

        )

        ############################################################
        # Keep Only Successful Outputs
        ############################################################

        successful_outputs = {

            name: result

            for name, result in specialist_outputs.items()

            if result.get(

                "status"

            ) == "completed"

        }

        ############################################################
        # Collaborative Reasoning
        ############################################################

        logger.info(

            "Running Collaborative Reasoning"

        )

        reasoning = collaborative_engine.collaborative_reasoning(

            context,

            successful_outputs

        )

        ############################################################
        # Executive Decision
        ############################################################

        logger.info(

            "Running Executive Decision"

        )

        executive_precheck = trustai.review("ExecutiveAgent")

        if executive_precheck.decision.action == "reject":

            logger.warning(

                "TRUSTAI rejected ExecutiveAgent: "
                f"{executive_precheck.decision.rationale}"

            )

            executive = {

                "status": "rejected",

                "confidence": 0,

                "error": (
                    "Rejected by TRUSTAI governance: "
                    + executive_precheck.decision.rationale
                ),

                "governance": asdict(executive_precheck)

            }

        else:

            try:

                executive = executive_agent.execute(

                    context=context,

                    reasoning=reasoning

                )

            except Exception as e:

                logger.exception(e)

                executive = {

                    "status":

                        "failed",

                    "confidence":

                        0,

                    "error":

                        str(e)

                }

            executive_record = trustai.record_outcome(
                "ExecutiveAgent",
                executive
            )

            executive["governance"] = asdict(executive_record)

        ############################################################
        # Recommendation
        ############################################################

        logger.info(

            "Running Recommendation Agent"

        )

        recommendation_precheck = trustai.review("RecommendationAgent")

        if recommendation_precheck.decision.action == "reject":

            logger.warning(

                "TRUSTAI rejected RecommendationAgent: "
                f"{recommendation_precheck.decision.rationale}"

            )

            recommendation = {

                "agent": "RecommendationAgent",

                "status": "rejected",

                "confidence": 0,

                "error": (
                    "Rejected by TRUSTAI governance: "
                    + recommendation_precheck.decision.rationale
                ),

                "governance": asdict(recommendation_precheck)

            }

        else:

            try:

                recommendation = recommendation_agent.execute(

                    context=context,

                    reasoning=reasoning,

                    executive=executive

                )

            except Exception as e:

                logger.exception(e)

                recommendation = {

                    "agent":

                        "RecommendationAgent",

                    "status":

                        "failed",

                    "confidence":

                        0,

                    "error":

                        str(e)

                }

            recommendation_record = trustai.record_outcome(
                "RecommendationAgent",
                recommendation
            )

            recommendation["governance"] = asdict(recommendation_record)

        ############################################################
        # Module 5H
        # Continuous Learning Engine
        #
        # Feeds the same recommendation outcome into the crop-level
        # trust dimension (app/learning/), which reuses TRUSTAI's own
        # evidence/trust/risk/decision machinery keyed by crop instead
        # of by agent. Runs for the rejected branch too -- a rejection
        # is still informative about this crop's pipeline maturity.
        ############################################################

        learning_record = continuous_learning_engine.record_recommendation_outcome(
            context.get("crop"),
            recommendation
        )

        ############################################################
        # Module 5G
        # Explainable Recommendation
        ############################################################

        logger.info(

            "Generating Explainability Report"

        )

        try:

            explanation = explanation_engine.explain(

                context=context,

                specialists=successful_outputs,

                reasoning=reasoning,

                executive_decision=executive,

                recommendation=recommendation

            )

        except Exception as e:

            logger.exception(e)

            explanation = {

                "status":

                    "failed",

                "confidence":

                    0,

                "error":

                    str(e)

            }

        ############################################################
        # Execution Statistics
        ############################################################

        completed = len(

            successful_outputs

        )

        unavailable_agents = [

            name

            for name, result in specialist_outputs.items()

            if str(
                result.get(
                    "status",
                    ""
                )
            ).strip().lower() == "unavailable"

        ]

        failed = (

            len(

                specialist_outputs

            )

            -

            completed

            -

            len(
                unavailable_agents
            )

        )

        ############################################################
        # Final Result
        ############################################################

        return {            ########################################################
            # Planner
            ########################################################

            "goal":

                plan["goal"],

            "execution_plan":

                plan["execution_plan"],

            ########################################################
            # Specialist Outputs
            ########################################################

            "specialists":

                specialist_outputs,

            ########################################################
            # Collaborative Reasoning
            ########################################################

            "reasoning":

                reasoning,

            ########################################################
            # Executive Decision
            ########################################################

            "executive":

                executive,

            ########################################################
            # Recommendation
            ########################################################

            "recommendation":

                recommendation,

            ########################################################
            # Module 5G
            # Explainability
            ########################################################

            "explanation":

                explanation.to_dict()

                if hasattr(

                    explanation,

                    "to_dict"

                )

                else explanation,

            ########################################################
            # TRUSTAI Governance
            ########################################################

            "governance": {

                "agent_trust": trustai.snapshot(),

                "crop_learning": {

                    "crop": context.get("crop"),

                    "trust_mean": round(learning_record.posterior_mean, 4),

                    "decision": learning_record.decision.action,

                    "all_crops": continuous_learning_engine.snapshot()

                },

                "recommendation_requires_review": (

                    recommendation.get("governance", {})
                    .get("decision", {})
                    .get("action")

                ) == "human_review",

                "recommendation_rejected": (

                    recommendation.get("status")

                ) == "rejected"

            },

            ########################################################
            # Overall Confidence
            ########################################################

            "confidence":

                executive.get(

                    "confidence",

                    getattr(

                        reasoning,

                        "confidence",

                        0

                    )

                ),

            ########################################################
            # Statistics
            ########################################################

            "statistics": {

                ####################################################
                # Planner
                ####################################################

                "agents_planned":

                    len(

                        plan["execution_plan"]

                    ),

                ####################################################
                # Specialists
                ####################################################

                "specialist_agents":

                    len(

                        successful_outputs

                    ),

                "agents_completed":

                    completed,

                "agents_failed":

                    failed,

                "agents_unavailable":

                    len(
                        unavailable_agents
                    ),

                "unavailable_agents":

                    unavailable_agents,

                ####################################################
                # Confidence
                ####################################################

                "planner_confidence":

                    plan.get(

                        "confidence",

                        0

                    ),

                "reasoning_confidence":

                    getattr(

                        reasoning,

                        "confidence",

                        0

                    ),

                "executive_confidence":

                    executive.get(

                        "confidence",

                        0

                    ),

                "explanation_confidence":

                    explanation.overall_confidence

                    if hasattr(

                        explanation,

                        "overall_confidence"

                    )

                    else 0,

                ####################################################
                # Explainability
                ####################################################

                "decision_trace_steps":

                    len(

                        explanation.decision_trace

                    )

                    if hasattr(

                        explanation,

                        "decision_trace"

                    )

                    else 0,

                "evidence_sources":

                    len(

                        explanation.evidence

                    )

                    if hasattr(

                        explanation,

                        "evidence"

                    )

                    else 0,

                "limitations":

                    len(

                        explanation.limitations

                    )

                    if hasattr(

                        explanation,

                        "limitations"

                    )

                    else 0,

                "monitoring_items":

                    len(

                        explanation.monitoring_plan

                    )

                    if hasattr(

                        explanation,

                        "monitoring_plan"

                    )

                    else 0,

                ####################################################
                # Models
                ####################################################

                "planner_model":

                    get_provider("planner"),

                "reasoning_model":

                    get_provider("collaborative"),

                # The executive decision is a deterministic rule engine
                # (app/executive/executive_engine.py infer_decision) --
                # no LLM is ever called for this stage, so there is no
                # provider to report.
                "executive_model":

                    "deterministic (rule-based, no LLM)",

                "recommendation_model":

                    get_provider("recommendation"),

                "explanation_model":

                    get_provider("explanation")

            }

        }


##########################################################################
# Singleton
##########################################################################

executor = DynamicExecutor()