"""
==========================================================================
AgriMind

Crop Profile Builder

Uses Ollama to generate a crop profile.

Pipeline

Ollama
    ↓
JSON Parsing
    ↓
Validation
    ↓
Normalization
    ↓
Return Canonical Profile

Author : AgriMind Team
==========================================================================
"""

import json

from app.prompts.crop_profile_prompt import CROP_PROFILE_PROMPT
from app.utils.ollama_client import ollama_client
from app.knowledge.crop_profile_validator import crop_profile_validator


class CropProfileBuilder:

    """
    Builds canonical crop profiles using Ollama.
    """

    ####################################################################
    # Build Prompt
    ####################################################################

    def build_prompt(self, crop):

        return f"""
{CROP_PROFILE_PROMPT}

======================================================================

Crop Name

{crop}

======================================================================

Generate the COMPLETE crop profile.

The JSON MUST strictly follow the schema.

Do not explain.

Return ONLY valid JSON.
"""

    ####################################################################
    # Parse JSON
    ####################################################################

    def parse(self, response):

        if response is None:
            raise ValueError("Ollama returned no response.")

        response = response.strip()

        response = response.replace("```json", "")
        response = response.replace("```", "")
        response = response.strip()

        start = response.find("{")
        end = response.rfind("}")

        if start == -1 or end == -1:
            raise ValueError("Ollama did not return valid JSON.")

        json_text = response[start:end + 1]

        try:
            return json.loads(json_text)

        except json.JSONDecodeError as e:

            raise ValueError(
                f"Invalid JSON generated by Ollama:\n{e}"
            )

    ####################################################################
    # Build Profile
    ####################################################################

    def build(self, crop):

        print(f"Generating knowledge for '{crop}' using Ollama...")

        prompt = self.build_prompt(crop)

        raw = ollama_client.generate(

            prompt=prompt,

            system_prompt=(
                "You are an agricultural scientist. "
                "Return ONLY valid JSON."
            ),

            temperature=0.2

        )

        profile = self.parse(raw)

        ############################################################
        # Metadata
        #
        # Force the requested crop name onto the profile rather than
        # trusting whatever string the LLM chose to echo back (e.g.
        # "Common Wheat" instead of "wheat"). The repository caches
        # by crop["crop"].lower(), so any drift here means every
        # future lookup for the actual crop name misses the cache and
        # silently regenerates -- and re-pays for -- the whole profile
        # via the LLM. This was confirmed happening for "wheat": 4+
        # successful runs, never once cached.
        ############################################################

        profile["crop"] = crop.lower().strip()

        profile["generated_by"] = "Ollama"

        ############################################################
        # Canonical Validation
        ############################################################

        profile = crop_profile_validator.validate(profile)

        print("[OK] Crop profile validated.")

        return profile

    ####################################################################
    # Rebuild Existing Profile
    ####################################################################

    def rebuild(self, crop):

        print(f"Rebuilding crop profile for '{crop}'...")

        return self.build(crop)


##########################################################################

crop_profile_builder = CropProfileBuilder()